// Mock data — easily swappable with real backend responses later.
export const MOCK_ORDERS = [
  {
    id: "LGD-29402",
    customer: "PT. Samudera Raya",
    initials: "PT",
    avatarColor: "bg-amber-100 text-amber-700",
    phone: "081365765516",
    date: "12 Okt 2023, 14:20",
    destination: "Surabaya, IDN",
    destLabel: "Gudang Utama A1",
    cargoType: "Cargo Laut",
    weight: "2.4 Ton",
    status: "Menunggu Verifikasi",
    deliveryStatus: "Diproses",
    invoiceUploaded: false,
    verified: false,
    manifestId: "LOG-8829",
    sender: { name: "PT AKU CINTA KAMU", pic: "DONI SIHOMBING", phone: "083345627189" },
    receiver: { name: "PT AKU TOLAK KAMU", pic: "RISTI SITUMEANG", phone: "089976543215" },
    cargo: { title: "Sparepart Otomotif & Mesin", weight: "2.450 KG", packageType: "Ban", totalPackage: "1" },
    vehicle: { type: "Truck", capacity: "4.000 Kg", image: "/images/isuzu-truck.jpg" },
    route: {
      pickup: { city: "Jakarta Utara", name: "Kawasan Industri Pulogadung", address: "Blok C No. 12, Pergudangan Logistics, Jakarta 13920" },
      dropoff: { city: "Surabaya", name: "Margomulyo Permai", address: "Jl. Greges Jaya II, Pergudangan B-14, Surabaya 60183" },
    },
    driver: { name: "", plate: "" },
  },
  {
    id: "LGD-29405",
    customer: "Andi Maulana",
    initials: "AM",
    avatarColor: "bg-gray-200 text-gray-700",
    phone: "081365765516",
    date: "12 Okt 2023, 15:45",
    destination: "Semarang, IDN",
    destLabel: "Distribusi Retail",
    cargoType: "Trucking",
    weight: "850 Kg",
    status: "Menunggu Verifikasi",
    deliveryStatus: "Diproses",
    invoiceUploaded: false,
    verified: false,
    manifestId: "LOG-8830",
    sender: { name: "PT Maju Jaya", pic: "BUDI SANTOSO", phone: "081234567890" },
    receiver: { name: "Toko Retail Semarang", pic: "WAHYU PUTRA", phone: "082234567891" },
    cargo: { title: "Elektronik Rumah Tangga", weight: "850 KG", packageType: "Box", totalPackage: "12" },
    vehicle: { type: "Truck", capacity: "2.000 Kg", image: "/images/isuzu-truck.jpg" },
    route: {
      pickup: { city: "Jakarta Timur", name: "Cakung Industrial", address: "Jl. Cakung Cilincing, Jakarta 13910" },
      dropoff: { city: "Semarang", name: "Gudang Tanah Mas", address: "Jl. Tanah Mas Raya, Semarang 50177" },
    },
    driver: { name: "", plate: "" },
  },
  {
    id: "LGD-29408",
    customer: "Global Food Corp",
    initials: "GF",
    avatarColor: "bg-amber-100 text-amber-700",
    phone: "081365765516",
    date: "12 Okt 2023, 16:10",
    destination: "Medan, IDN",
    destLabel: "Hub Kualanamu",
    cargoType: "Cargo Udara",
    weight: "120 Kg",
    status: "Menunggu Verifikasi",
    deliveryStatus: "Diproses",
    invoiceUploaded: false,
    verified: false,
    manifestId: "LOG-8831",
    sender: { name: "Global Food HQ", pic: "RINA WIJAYA", phone: "081111222333" },
    receiver: { name: "Distributor Medan", pic: "AGUS SETIAWAN", phone: "082222333444" },
    cargo: { title: "Makanan Beku Premium", weight: "120 KG", packageType: "Cooler Box", totalPackage: "8" },
    vehicle: { type: "Air Cargo", capacity: "500 Kg", image: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=400&h=300&fit=crop" },
    route: {
      pickup: { city: "Tangerang", name: "Bandara Soekarno-Hatta Cargo", address: "Terminal Kargo, Tangerang 19120" },
      dropoff: { city: "Medan", name: "Hub Kualanamu", address: "Bandara Kualanamu, Medan 20371" },
    },
    driver: { name: "", plate: "" },
  },
  {
    id: "LGD-29412",
    customer: "Eka Lestari",
    initials: "EL",
    avatarColor: "bg-gray-200 text-gray-700",
    phone: "081365765516",
    date: "13 Okt 2023, 08:30",
    destination: "Bandung, IDN",
    destLabel: "Toko Retail",
    cargoType: "Trucking",
    weight: "320 Kg",
    status: "Menunggu Verifikasi",
    deliveryStatus: "Diproses",
    invoiceUploaded: false,
    verified: false,
    manifestId: "LOG-8832",
    sender: { name: "CV Sejahtera", pic: "EKA LESTARI", phone: "083344556677" },
    receiver: { name: "Toko Bandung", pic: "DEWI ANGGRAINI", phone: "084455667788" },
    cargo: { title: "Pakaian & Tekstil", weight: "320 KG", packageType: "Karung", totalPackage: "20" },
    vehicle: { type: "Pickup", capacity: "1.000 Kg", image: "/images/pickup-truck.jpg" },
    route: {
      pickup: { city: "Jakarta Barat", name: "Tanah Abang Center", address: "Pasar Tanah Abang Blok A, Jakarta 10250" },
      dropoff: { city: "Bandung", name: "Pasar Baru Bandung", address: "Jl. Otto Iskandar Dinata, Bandung 40117" },
    },
    driver: { name: "", plate: "" },
  },
];

export const MOCK_COMPANY = {
  name: "CV. Mandiri Perkasa Logis",
  legalName: "CV. Mandiri Perkasa Logis",
  taxId: "01.234.567.8-901.000",
  email: "info@mpllogistics.co.id",
  phone: "+62 21 5567 8900",
  website: "www.mpllogistics.co.id",
  address: "Jl. Raya Cakung-Cilincing No. 88, Jakarta Utara, DKI Jakarta 14130",
  description: "Penyedia layanan logistik darat, laut, dan udara terpercaya sejak 2008. Melayani distribusi nasional dengan jangkauan ke seluruh Indonesia.",
  founded: "2008",
  employees: "150+",
};

export const MOCK_PROFILE = {
  name: "Zuhri",
  role: "SENIOR DISPATCHER",
  email: "zuhri@mpllogistics.co.id",
  phone: "081365765516",
  joinDate: "15 Mar 2019",
  branch: "Jakarta Pusat",
};

export const MOCK_CHATBOT = {
  enabled: true,
  greeting: "Halo! Selamat datang di MPL Logistics. Ada yang bisa kami bantu?",
  fallback: "Mohon maaf, saya belum mengerti pertanyaan Anda. Silakan hubungi customer service kami di 021-5567 8900.",
  faqs: [
    { id: 1, question: "Bagaimana cara melacak pesanan?", answer: "Masukkan nomor resi pada halaman 'Lacak Pesanan' untuk melihat status terkini." },
    { id: 2, question: "Berapa lama estimasi pengiriman?", answer: "Estimasi 2-5 hari kerja untuk darat, 1-2 hari untuk udara, tergantung tujuan." },
    { id: 3, question: "Apakah ada asuransi pengiriman?", answer: "Ya, semua paket di atas 100 KG otomatis tercover asuransi all-risk." },
  ],
};

export const DELIVERY_STATUSES = ["Diproses", "Barang Diambil", "Dalam Perjalanan", "Tiba di Tujuan"];
